security:
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: $2y$13$QSbUgO3WNIfzAVe0/fqOfe9wzCBXLM7/5NEN.vb8gbvddRBDzuehq
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$13$LF5Cy.7VmhsRkrwjxr9L9uv8XBvpN0XmQB24JTvBLuqPmBcPISMqG
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /                
                #always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/ascuns, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
           
    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_USER]
        ROLE_USER: [ROLE_USER]